# Generated by Django 5.1.4 on 2024-12-29 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rest_framework_api_key", "0005_auto_20220110_1102"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_link", models.URLField(max_length=250)),
                ("shorted_link", models.CharField(max_length=10, unique=True)),
                ("redirect_counter", models.PositiveIntegerField(default=0)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_framework_api_key.apikey",
                    ),
                ),
            ],
        ),
    ]
